### ISSUE TITLE
Add autologging configuration to app config

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture_App#1076] opened 2016-07-19 20:53 UTC
2.10.0 will have a flag named 'autologger' that will tell you if it supports autologging. The app will need a configuration section to enable/disable it and set the values for start/stop.

**Comment by brentpicasso** [comment] 2017-06-03 06:50
duplicate of #1321

**Closed by brentpicasso** 2017-06-03 06:50 UTC
