### ISSUE TITLE
autodetect (wifi) fails to recover

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture_App#1225] opened 2016-09-14 16:16 UTC
Caught this in the act, need to repro and fix. 

I/python  (30102): {"beacon":{"name":"RCT","port":7223,"serial":"360026000157335239383620","ip":["0.0.0.0
I/python  (30102): [ERROR             ] [RCPAPI      ] Error running auto detect: Extra data: line 2 column 1 - line 2 column 87 (char 106 - 192)
I/python  (30102): [ERROR             ] [Traceback (most recent call last)]
I/python  (30102):   File "/home/brent/git-projects/RaceCapture_App/.buildozer/android/app/autosportlabs/racecapture/api/rcpapi.py", line 800, in auto_detect_worker
I/python  (30102):   File "/home/brent/git-projects/RaceCapture_App/.buildozer/android/app/autosportlabs/comms/socket/socketcomm.py", line 84, in get_available_devices
I/python  (30102):   File "/home/brent/git-projects/RaceCapture_App/.buildozer/android/app/autosportlabs/comms/socket/socketconnection.py", line 61, in get_available_devices
I/python  (30102):   File "/home/brent/git-projects/RaceCapture_App/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/json/__init__.py", line 326, in loads
I/python  (30102):   File "/home/brent/git-projects/RaceCapture_App/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/json/decoder.py", line 369, in decode

**Comment by ryandoherty** [comment] 2016-09-21 17:08
Looks like dupe of autosportlabs/RaceCapture_App#1189

**Closed by ryandoherty** 2016-09-21 17:08 UTC
Labels: bug
