### ISSUE TITLE
Lines not drawn in graph in analysis view on android

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture_App#801] opened 2016-01-11 23:18 UTC
Nexus 6P, Android 6.0.1. When I import a session and tap on a lap, no lines are drawn on the graph.

**Comment by brentpicasso** [comment] 2016-01-11 23:36
This is caused by a logfile with incorrect metadata. This will be addressed by #762

**Closed by brentpicasso** 2016-01-11 23:36 UTC
