### ISSUE TITLE
Analysis view state not saved between app restarts

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture_App#843] opened 2016-01-28 17:16 UTC
STR:

1) Open analysis view
2) Load a session and a lap 
3) Add a channel to the bottom graph
4) Kill app
5) Reopen app
6) Go to analysis view
7) See that no laps are loaded and when laps are selected, the bottom graph does not graph anything

Expected behavior: analysis view has the same state as I left it.

**Comment by brentpicasso** [comment] 2016-01-28 17:20
duplicate of #764

**Closed by brentpicasso** 2016-01-28 17:20 UTC
